[workspace]
resolver = "2"
members = [
    "crates/*"
]

[workspace.package]
version = "0.1.0-dev"
authors = ["haruki7049 <tontonkirikiri@gmail.com>"]
repository = "https://github.com/haruki7049/ferlibc.git"
license = "Apache OR MIT"

[workspace.metadata.crane]
name = "ferlibc"
